services:
  - type: web
    name: hoatax
    env: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn HOA_tax.wsgi:application
    # Other settings...
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DJANGO_DEBUG
        value: false
    disk:
      name: media
      mountPath: /var/lib/render/disk
      sizeGB: 10