services:
  - type: web
    name: hoatax
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn HOA_tax.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DJANGO_DEBUG
        value: false
    disk:
      name: media
      mountPath: /opt/render/project/media
      sizeGB: 10