# Generated by Django 5.1.1 on 2024-09-25 17:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('association_name', models.CharField(max_length=255)),
                ('mailing_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=20)),
                ('zoned', models.BooleanField(default=True)),
                ('ein', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message="EIN must be in the format 'XX-XXXXXXX'.", regex='^\\d{2}-\\d{7}$')])),
                ('formation_date', models.DateField()),
                ('association_type', models.CharField(choices=[('condo', 'Condominium'), ('homeowners', 'Homeowners')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Financial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_year', models.IntegerField(default=2023, help_text='The year this financial data pertains to')),
                ('name_change', models.BooleanField(default=False)),
                ('address_change', models.BooleanField(default=False)),
                ('prior_year_over_payment', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('extension_payment', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('estimated_payment', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('member_assessments', models.PositiveIntegerField(default=0)),
                ('capital_contribution', models.PositiveIntegerField(default=0)),
                ('moving_fees', models.PositiveIntegerField(default=0)),
                ('utilities', models.PositiveIntegerField(default=0)),
                ('late_fees', models.PositiveIntegerField(default=0)),
                ('fines', models.PositiveIntegerField(default=0)),
                ('other_exempt_income', models.PositiveBigIntegerField(default=0)),
                ('total_expenses', models.PositiveIntegerField(default=0)),
                ('interest', models.PositiveIntegerField(default=0)),
                ('dividends', models.PositiveIntegerField(default=0)),
                ('rentals', models.PositiveIntegerField(default=0)),
                ('non_exempt_income_description1', models.CharField(blank=True, max_length=100)),
                ('non_exempt_income_amount1', models.PositiveIntegerField(default=0)),
                ('non_exempt_income_description2', models.CharField(blank=True, max_length=100)),
                ('non_exempt_income_amount2', models.PositiveIntegerField(default=0)),
                ('non_exempt_income_description3', models.CharField(blank=True, max_length=100)),
                ('non_exempt_income_amount3', models.PositiveIntegerField(default=0)),
                ('tax_preparation', models.PositiveIntegerField(default=0)),
                ('management_fees', models.PositiveIntegerField(default=0)),
                ('administration_fees', models.PositiveIntegerField(default=0)),
                ('audit_fees', models.PositiveIntegerField(default=0)),
                ('allocated_rental_expenses', models.PositiveIntegerField(default=0)),
                ('non_exempt_expense_description1', models.CharField(blank=True, max_length=100)),
                ('non_exempt_expense_amount1', models.PositiveIntegerField(default=0)),
                ('non_exempt_expense_description2', models.CharField(blank=True, max_length=100)),
                ('non_exempt_expense_amount2', models.PositiveIntegerField(default=0)),
                ('non_exempt_expense_description3', models.CharField(blank=True, max_length=100)),
                ('non_exempt_expense_amount3', models.PositiveIntegerField(default=0)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tax_form.association')),
            ],
        ),
        migrations.CreateModel(
            name='Preparer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='D. Douglas, McLain', max_length=255)),
                ('signature', models.CharField(default='D. Douglas, McLain', max_length=255)),
                ('ptin', models.CharField(default='P01502513', max_length=20)),
                ('sign_date', models.DateField(blank=True, null=True)),
                ('firm_name', models.CharField(default='C.O.R.E. Services, LLC', max_length=255)),
                ('firm_ein', models.CharField(default='82-2426287', max_length=20)),
                ('firm_address', models.CharField(default='PO Box 8, Vancouver, WA 98666', max_length=255)),
                ('firm_phone', models.CharField(default='360-524-9665', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
