# Generated by Django 5.1.1 on 2024-09-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preparer',
            name='firm_address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='preparer',
            name='firm_ein',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='preparer',
            name='firm_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='preparer',
            name='firm_phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='preparer',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='preparer',
            name='ptin',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='preparer',
            name='signature',
            field=models.CharField(blank=True, help_text='Leave blank to use the name as signature', max_length=255),
        ),
    ]
