# Generated by Django 5.1.1 on 2024-09-26 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_form', '0002_alter_preparer_firm_address_alter_preparer_firm_ein_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preparer',
            name='signature',
            field=models.CharField(max_length=255),
        ),
    ]
