# Generated by Django 5.1.1 on 2024-09-28 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_form', '0003_alter_preparer_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='association',
            name='contact_first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='association',
            name='contact_last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='association',
            name='fiscal_year_end_month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=12),
        ),
        migrations.AddField(
            model_name='financial',
            name='engagement_letter',
            field=models.FileField(blank=True, null=True, upload_to='engagement_letters/'),
        ),
        migrations.AddField(
            model_name='financial',
            name='engagement_letter_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='financial',
            unique_together={('association', 'tax_year')},
        ),
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filed', models.BooleanField(default=False, help_text='Indicates whether the extension has been filed')),
                ('filed_date', models.DateField(blank=True, help_text='The date the extension was filed', null=True)),
                ('form_7004', models.FileField(blank=True, null=True, upload_to='extensions/')),
                ('financial', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extension', to='tax_form.financial')),
            ],
        ),
    ]
