# Generated by Django 5.1.1 on 2024-10-01 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_form', '0004_association_contact_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedTaxReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_prepared', models.DateField(help_text='The date the tax return was prepared')),
                ('tax_return_pdf', models.FileField(blank=True, null=True, upload_to='completed_tax_returns/')),
                ('financial', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='completed_tax_return', to='tax_form.financial')),
            ],
        ),
    ]
