# Generated by Django 5.1.1 on 2024-10-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_form', '0005_completedtaxreturn'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedtaxreturn',
            name='return_filed',
            field=models.BooleanField(default=False, help_text='Indicates whether the tax return has been filed'),
        ),
        migrations.AlterField(
            model_name='completedtaxreturn',
            name='date_prepared',
            field=models.DateField(blank=True, help_text='The date the tax return was prepared', null=True),
        ),
    ]
