# Generated by Django 5.1.1 on 2024-11-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_form', '0006_completedtaxreturn_return_filed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extension',
            name='balance_due',
            field=models.PositiveIntegerField(default=0, help_text='Form 7004 Line 8 - Balance due'),
        ),
        migrations.AddField(
            model_name='extension',
            name='tentative_tax',
            field=models.PositiveIntegerField(default=0, help_text='Form 7004 Line 6 - Tentative total tax'),
        ),
        migrations.AddField(
            model_name='extension',
            name='total_payments',
            field=models.PositiveIntegerField(default=0, help_text='Form 7004 Line 7 - Total payments and credits'),
        ),
    ]
