# Generated by Django 5.1.1 on 2025-03-11 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_form', '0007_extension_balance_due_extension_tentative_tax_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngagementLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_year', models.IntegerField(default=2025, help_text='Tax year this engagement is for')),
                ('price', models.PositiveIntegerField(default=150, help_text='Price for tax preparation services')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_signed', models.DateField(blank=True, null=True)),
                ('signed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('signer_title', models.CharField(blank=True, max_length=100, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='engagement_letters/')),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_letters', to='tax_form.association')),
            ],
            options={
                'unique_together': {('association', 'tax_year')},
            },
        ),
    ]
