# Generated by Django 5.1.1 on 2025-03-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_form', '0008_engagementletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagementletter',
            name='signed_pdf',
            field=models.FileField(blank=True, null=True, upload_to='signed_engagement_letters/'),
        ),
        migrations.AddField(
            model_name='engagementletter',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('signed', 'Signed')], default='pending', max_length=10),
        ),
    ]
