# Generated by Django 5.1.1 on 2025-03-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_form', '0009_engagementletter_signed_pdf_engagementletter_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='financial',
            name='financial_info_pdf',
            field=models.FileField(blank=True, null=True, upload_to='financial_info/'),
        ),
    ]
