# Generated by Django 5.1.1 on 2025-03-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_form', '0010_financial_financial_info_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedtaxreturn',
            name='filing_status',
            field=models.CharField(choices=[('not_filed', 'Not Filed'), ('filed_by_dynamite', 'Filed by Dynamite'), ('filed_by_association', 'Filed by Association')], default='not_filed', help_text='Who filed the tax return', max_length=20),
        ),
        migrations.AddField(
            model_name='completedtaxreturn',
            name='sent_date',
            field=models.DateField(blank=True, help_text='The date the tax return was sent for signature', null=True),
        ),
        migrations.AddField(
            model_name='completedtaxreturn',
            name='sent_for_signature',
            field=models.BooleanField(default=False, help_text='Indicates whether the tax return was sent for signature'),
        ),
        migrations.AddField(
            model_name='completedtaxreturn',
            name='sent_tax_return_pdf',
            field=models.FileField(blank=True, help_text='PDF of the tax return sent for signature', null=True, upload_to='sent_tax_returns/'),
        ),
        migrations.AlterField(
            model_name='completedtaxreturn',
            name='tax_return_pdf',
            field=models.FileField(blank=True, help_text='PDF of the signed tax return', null=True, upload_to='completed_tax_returns/'),
        ),
    ]
