# Generated by Django 5.1.1 on 2025-03-14 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_form', '0011_completedtaxreturn_filing_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociationFilingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_year', models.IntegerField(help_text='The tax year this status applies to')),
                ('prepare_return', models.BooleanField(default=True, help_text="If False, we won't be preparing a tax return for this association this year")),
                ('not_filing_reason', models.CharField(blank=True, help_text='Reason for not preparing a tax return', max_length=255)),
                ('invoiced', models.BooleanField(default=False, help_text='Has this association been invoiced?')),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filing_statuses', to='tax_form.association')),
            ],
            options={
                'verbose_name_plural': 'Association Filing Statuses',
                'unique_together': {('association', 'tax_year')},
            },
        ),
    ]
