# Generated by Django 5.1.1 on 2025-03-17 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_form', '0012_associationfilingstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Management Company',
                'verbose_name_plural': 'Management Companies',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='association',
            name='is_self_managed',
            field=models.BooleanField(default=True, help_text='Check if this association is self-managed (no management company)'),
        ),
        migrations.AddField(
            model_name='association',
            name='management_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associations', to='tax_form.managementcompany'),
        ),
    ]
