# Generated by Django 5.1.1 on 2026-01-03 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_form', '0013_managementcompany_association_is_self_managed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngagementLetterTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_year', models.IntegerField(help_text='Tax year this template applies to', unique=True)),
                ('services_text', models.TextField(default='Dynamite Management, LLC will prepare the federal Form 1120H for the tax year ending December 31, {tax_year}. Our services will include the preparation of the tax forms based on the financial information provided by you. It is your responsibility to provide all the necessary information required for the preparation of complete and accurate returns.', help_text='Services section text. Use {tax_year} as placeholder.')),
                ('fees_text', models.TextField(default='The fee for the preparation of the Form 1120H will be: ${price}. These fees are based on the assumption that all information provided by you is accurate and complete and that you will provide all required information in a timely manner. Any additional services or consultations beyond the scope of this engagement will be billed separately.', help_text='Fees section text. Use {price} as placeholder.')),
                ('responsibilities_text', models.TextField(default='It is your responsibility to provide all the information required for the preparation of the tax returns. You are also responsible for reviewing the returns for accuracy and completeness before they are filed. You are responsible for the payment of all taxes due. You should retain all the documents and other data that form the basis of this return for at least seven (7) years.\n\nBy signing below, you are also taking responsibility for making all management decisions and performing all management functions; for designating an individual with suitable skill, knowledge, or experience to oversee the tax services provided.', help_text='Responsibilities section text.')),
                ('consent_text', models.TextField(default="You acknowledge and agree that Dynamite Management, LLC may use your association's tax return information provided for the purpose of preparing your tax returns.", help_text='Consent section text.')),
                ('default_price', models.PositiveIntegerField(default=150, help_text='Default price for new engagement letters')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-tax_year'],
            },
        ),
        migrations.AddField(
            model_name='engagementletter',
            name='custom_consent_text',
            field=models.TextField(blank=True, help_text='Override consent text for this letter only', null=True),
        ),
        migrations.AddField(
            model_name='engagementletter',
            name='custom_fees_text',
            field=models.TextField(blank=True, help_text='Override fees text for this letter only', null=True),
        ),
        migrations.AddField(
            model_name='engagementletter',
            name='custom_responsibilities_text',
            field=models.TextField(blank=True, help_text='Override responsibilities text for this letter only', null=True),
        ),
        migrations.AddField(
            model_name='engagementletter',
            name='custom_services_text',
            field=models.TextField(blank=True, help_text='Override services text for this letter only', null=True),
        ),
        migrations.AlterField(
            model_name='engagementletter',
            name='tax_year',
            field=models.IntegerField(default=2026, help_text='Tax year this engagement is for'),
        ),
    ]
