# Generated by Django 5.1.1 on 2026-01-03 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_form', '0014_engagement_letter_templates'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateEngagementTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('WA', 'Washington'), ('OR', 'Oregon'), ('IL', 'Illinois'), ('CA', 'California'), ('TX', 'Texas'), ('FL', 'Florida'), ('AZ', 'Arizona'), ('NV', 'Nevada'), ('CO', 'Colorado')], max_length=2, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this state requires additional engagement letter content')),
                ('state_services_text', models.TextField(blank=True, help_text='Additional services text for this state. Use {tax_year} and {state_name} as placeholders.')),
                ('default_state_fee', models.PositiveIntegerField(default=0, help_text='Default additional fee for state filing')),
                ('state_fee_text', models.TextField(blank=True, default='Additionally, there will be a fee of ${state_fee} for the preparation of the {state_name} state filing.', help_text='Text describing the state fee. Use {state_fee} and {state_name} as placeholders.')),
                ('state_disclosure_text', models.TextField(blank=True, help_text='State-specific disclosure or legal requirements text.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['state'],
            },
        ),
        migrations.AddField(
            model_name='engagementletter',
            name='state_fee',
            field=models.PositiveIntegerField(default=0, help_text='Additional fee for state filing (0 if no state filing needed)'),
        ),
        migrations.AlterField(
            model_name='engagementletter',
            name='price',
            field=models.PositiveIntegerField(default=150, help_text='Price for federal tax preparation services'),
        ),
    ]
