# Generated by Django 5.1.1 on 2026-01-03 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_form', '0015_state_engagement_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='stateengagementtemplate',
            name='state_form_name',
            field=models.CharField(blank=True, help_text="Name of the state form (e.g., 'Form IL-1120-ST', 'Annual Report')", max_length=100),
        ),
        migrations.AlterField(
            model_name='stateengagementtemplate',
            name='state_services_text',
            field=models.TextField(blank=True, help_text='Additional services text for this state. Use {tax_year}, {state_name}, and {state_form_name} as placeholders.'),
        ),
    ]
