# Generated by Django 5.1.1 on 2026-01-06 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_form', '0016_add_state_form_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='filing_state',
            field=models.CharField(blank=True, choices=[('', 'Same as mailing address'), ('WA', 'Washington'), ('OR', 'Oregon'), ('IL', 'Illinois'), ('CA', 'California'), ('TX', 'Texas'), ('FL', 'Florida'), ('AZ', 'Arizona'), ('NV', 'Nevada'), ('CO', 'Colorado')], default='', help_text='State where the association files state tax returns (if different from mailing address)', max_length=2),
        ),
    ]
