# Generated by Django 5.1.1 on 2026-02-23 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_form', '0018_expand_state_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='room_suite',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
