# Generated by Django 5.1.1 on 2026-02-23 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_form', '0019_association_room_suite'),
    ]

    operations = [
        migrations.AddField(
            model_name='financial',
            name='amended_return',
            field=models.BooleanField(default=False),
        ),
    ]
