# Generated by Django 5.1.1 on 2026-02-26 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_form', '0020_financial_amended_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='state_tax_id',
            field=models.CharField(blank=True, default='', help_text='State tax ID or corporate file/charter number (e.g., IL Secretary of State number)', max_length=50),
        ),
    ]
