# Generated by Django 5.1.1 on 2026-02-26 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_form', '0021_add_state_tax_id_to_association'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='naics_code',
            field=models.CharField(blank=True, default='', help_text='North American Industry Classification System (NAICS) code (e.g., 813990)', max_length=6),
        ),
        migrations.AddField(
            model_name='association',
            name='records_city',
            field=models.CharField(blank=True, default='', help_text='City where accounting records are kept', max_length=100),
        ),
        migrations.AddField(
            model_name='association',
            name='records_state',
            field=models.CharField(blank=True, default='', help_text='State where accounting records are kept', max_length=2),
        ),
        migrations.AddField(
            model_name='association',
            name='records_zip',
            field=models.CharField(blank=True, default='', help_text='ZIP code where accounting records are kept', max_length=10),
        ),
    ]
