# Generated by Django 5.1.1 on 2026-03-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_form', '0022_add_naics_and_records_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='state_care_of',
            field=models.CharField(blank=True, default='', help_text='C/O line for state tax form mailing address (leave blank to use management company name)', max_length=255),
        ),
    ]
