# Generated by Django 5.1.1 on 2026-03-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_form', '0023_add_state_care_of'),
    ]

    operations = [
        migrations.RenameField(
            model_name='association',
            old_name='state_care_of',
            new_name='care_of',
        ),
        migrations.AlterField(
            model_name='association',
            name='care_of',
            field=models.CharField(blank=True, default='', help_text='Care of name (e.g., management company). Prepended to address on 1120-H, separate line on state forms.', max_length=255, verbose_name='C/O'),
        ),
    ]
