# Generated by Django 5.1.1 on 2026-03-14 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_form', '0024_rename_state_care_of_to_care_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='financial',
            name='state_local_taxes',
            field=models.PositiveIntegerField(default=0, help_text='State and local income taxes paid (prior year)'),
        ),
    ]
