# Generated by Django 5.1.1 on 2026-03-21 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_form', '0026_add_invoice_payment_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementcompany',
            name='extraction_hints',
            field=models.TextField(blank=True, default='', help_text="Hints for AI financial data extraction. Describe how this company formats their financial reports, e.g.: 'Assessments are labeled Maintenance Fee Income. Laundry income is under Other Revenue. Reports have Budget/Actual/Variance columns — use the Actual column.'"),
        ),
        migrations.CreateModel(
            name='ExtractionCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(help_text='The form field that was corrected', max_length=100)),
                ('ai_value', models.CharField(help_text='The value AI originally extracted', max_length=255)),
                ('corrected_value', models.CharField(help_text='The value the user corrected it to', max_length=255)),
                ('source_label', models.CharField(blank=True, default='', help_text='The label/line item name from the PDF that was misinterpreted (optional)', max_length=255)),
                ('notes', models.TextField(blank=True, default='', help_text='Optional notes explaining the correction')),
                ('tax_year', models.IntegerField(help_text='Tax year of the financial data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('management_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_corrections', to='tax_form.managementcompany')),
            ],
            options={
                'verbose_name': 'Extraction Correction',
                'verbose_name_plural': 'Extraction Corrections',
                'ordering': ['-created_at'],
            },
        ),
    ]
