# Generated by Django 5.1.1 on 2026-03-21 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_form', '0027_add_extraction_hints_and_corrections'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedtaxreturn',
            name='reviewed',
            field=models.BooleanField(default=False, help_text='Indicates whether the completed return has been reviewed'),
        ),
        migrations.AddField(
            model_name='completedtaxreturn',
            name='reviewed_date',
            field=models.DateField(blank=True, help_text='The date the return was reviewed', null=True),
        ),
    ]
