# Generated by Django 5.1.1 on 2026-03-21 03:29

from django.db import migrations


def remove_kristi_mclain_preparer(apps, schema_editor):
    Preparer = apps.get_model('tax_form', 'Preparer')
    Preparer.objects.filter(name='Kristi McLain').delete()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tax_form', '0028_add_reviewed_fields_to_completed_tax_return'),
    ]

    operations = [
        migrations.RunPython(remove_kristi_mclain_preparer, noop),
    ]
